services:
  app:
    build: .
    image: pydev:latest
    working_dir: /project

    volumes:
      - .:/project
      - venv:/project/.venv
      - news-cleaner-venv:/project/src/news/.venv

    command:
      - sh
      - -c
      - |
        uv sync --frozen &&
        exec bash

volumes:
  venv:
  news-cleaner-venv: